pipeline {
    agent any

    environment {
        APP_DIR = 'java-jenkins-demo'
        APP_JAR = 'demo-1.0.jar'
        APP_PORT = '8081'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-ssh',
                    url: 'git@github.com:Siddharth-2110/java-devops-project.git'
            }
        }

        stage('Build') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                echo "Deploying application..."
                sudo cp ${APP_DIR}/target/${APP_JAR} /opt/java-demo/app.jar
                sudo systemctl restart java-demo
                '''
            }
        }

        stage('Verify') {
            steps {
                sh '''
                echo "Waiting for application to become healthy..."

                for i in {1..10}; do
                  if curl -sf http://localhost:${APP_PORT} > /dev/null; then
                    echo "✅ Application is UP"
                    exit 0
                  fi
                  echo "⏳ App not ready yet... retry $i"
                  sleep 3
                done

                echo "❌ Application failed to start"
                exit 1
                '''
            }
        }
    }

    post {
        success {
            echo "🎉 Deployment successful and verified!"
        }
        failure {
            echo "❌ Deployment failed. Check systemctl and app logs."
        }
    }
}

