pipeline {
    agent any

    environment {
        APP_DIR = 'java-jenkins-demo'
        APP_NAME = 'java-demo'
        JAR_NAME = 'demo-1.0.jar'
        DEPLOY_PATH = '/opt/java-demo/app.jar'
        SERVICE_NAME = 'java-demo'
        APP_PORT = '8081'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-ssh',
                    url: 'git@github.com:Siddharth-2110/java-devops-project.git'
            }
        }

        stage('Build') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                echo "Deploying application..."
                sudo cp ${APP_DIR}/target/${JAR_NAME} ${DEPLOY_PATH}
                sudo systemctl restart ${SERVICE_NAME}
                """
            }
        }

        stage('Verify') {
            steps {
                sh """
                echo "Verifying application..."
                sleep 3
                curl -f http://localhost:${APP_PORT}
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful. App running on port ${APP_PORT}"
        }
        failure {
            echo "❌ Deployment failed."
        }
    }
}

